In [43]:
#Входные данные: 1, 2, 3, 4, 5, -15

def count(a, sum):
    return a + sum


a = int(input('Введите число: '))
arr = []
result = 0
average_sum = 0
while True:
    result = count(a, result)
    arr.append(a)
    if result == 0:
        for i in arr:
            average_sum += i**2
        print(f"Ура, 0! \n Общая сумма квадратов всех введенных чисел: {average_sum}")
        break
    a = int(input(f'Сумма равна: {result} \n Введите число: '))
    pass

#Выходные данные

Ура, 0! 
 Общая сумма квадратов всех введенных чисел: 280


In [44]:
#Входные данные: 7
k = int(input())
chetcik = 0
for i in range(k):
    for j in range(i):
        if chetcik == k:
            break
        else:
            print(i,end=" ")
        chetcik += 1

#Выходные данные

1 2 2 3 3 3 4 

In [40]:
#Входные данные: НЕТ

import numpy as np
arr = np.random.rand(3, 3)
print(arr)
l = []
for i in range(len(arr)):
    for j in range(len(arr[i])):
        l.append(arr[i][j])
print(*l)
#Выходные данные

[[0.17680127 0.02976646 0.24649541]
 [0.34262911 0.43217646 0.84887325]
 [0.4982652  0.49037654 0.06340642]]
0.1768012691520956 0.02976646089597801 0.2464954080787305 0.34262911131308926 0.4321764587632134 0.8488732457987558 0.49826519654625656 0.4903765413596035 0.06340641546996306


In [40]:
#Входные данные:
A = [ 1,   2,   3,   4,   2,   1,   3,   4,   5,   6,   5,   4,   3,   2]
B = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']

result = {}

for index, i in enumerate(B):
    if i not in result:
        result[i] = A[index]
    else:
        result[i] += A[index]

print(result.items())
#Выходные данные

dict_items([('a', 17), ('b', 11), ('c', 17)])
