In [19]:
import os

def count(a, sum):
    return a + sum


a = int(input('Введите число: '))
arr = []
result = 0
average_sum = 0
while True:
    result = count(a, result)
    arr.append(a)
    if result == 0:
        for i in arr:
            average_sum += i**2
        print(f"Ура, 0! \n Общая сумма квадратов всех введенных чисел: {average_sum}")
        break
    a = int(input(f'Сумма равна: {result} \n Введите число: '))
    pass

Ура, 0! 
 Общая сумма квадратов всех введенных чисел: 3410


In [22]:
k = int(input())
chetcik = 0
for i in range(k):
    for j in range(i):
        if chetcik == k:
            break
        else:
            print(i,end=" ")
        chetcik += 1

1 2 2 3 3 3 4 

In [40]:
import numpy as np
arr = np.random.rand(3, 3)
print(arr)
l = []
for i in range(len(arr)):
    for j in range(len(arr[i])):
        l.append(arr[i][j])
print(*l)

[[0.17680127 0.02976646 0.24649541]
 [0.34262911 0.43217646 0.84887325]
 [0.4982652  0.49037654 0.06340642]]
0.1768012691520956 0.02976646089597801 0.2464954080787305 0.34262911131308926 0.4321764587632134 0.8488732457987558 0.49826519654625656 0.4903765413596035 0.06340641546996306


In [32]:
A = [ 1,   2,   3,   4,   2,   1,   3,   4,   5,   6,   5,   4,   3,   2]
B = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']

result = {}
asort = []
bsort = []
positoins = []
for index, i in enumerate(B):
    if i not in bsort:
        bsort.append(i)#(A[i])
        for jindex, j in enumerate(A):
            sum += A
print(bsort)
perem = 0
for jndex, j in enumerate(B):

    for index, i in enumerate(bsort):
        if i == j:
            perem += A[jndex]
    positoins.append(perem)

print(positoins)

['a', 'b', 'c']
[1, 2, 3, 4, 2, 1, 3, 4, 5, 6, 5, 4, 3, 2]


In [37]:
A = [ 1,   2,   3,   4,   2,   1,   3,   4,   5,   6,   5,   4,   3,   2]
B = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']

for i, j in enumerate(B):
    print(i, j, '-', B[i], A[i])



0 a - a 1
1 b - b 2
2 c - c 3
3 c - c 4
4 c - c 2
5 b - b 1
6 a - a 3
7 c - c 4
8 a - a 5
9 a - a 6
10 b - b 5
11 c - c 4
12 b - b 3
13 a - a 2


In [35]:
A = [ 1,   2,   3,   4,   2,   1,   3,   4,   5,   6,   5,   4,   3,   2]
B = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']

result = {}

for index, i in enumerate(B):
    if i not in result:
        result[i] = A[index]
    else:
        result[i] += A[index]

print(result.items())


dict_items([('a', 17), ('b', 11), ('c', 17)])


In [40]:
A = [ 1,   2,   3,   4,   2,   1,   3,   4,   5,   6,   5,   4,   3,   2]
B = ['a', 'b', 'c', 'c', 'c', 'b', 'a', 'c', 'a', 'a', 'b', 'c', 'b', 'a']

result = {}

for index, i in enumerate(B):
    if i not in result:
        result[i] = A[index]
    else:
        result[i] += A[index]

print(result.items())

dict_items([('a', 17), ('b', 11), ('c', 17)])
